version: "3"
services:
    application:
        build: ./
        image: registry.gitlab.com/ad-launcher/application-v2:test
        command: python manage.py runserver 0.0.0.0:8000
        env_file: .env
        ports:
            - 8000:8000
        volumes:
            - .:/application
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        env_file: .env
        ports: 
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
